### ISSUE TITLE
How to make it work on Wamp 3.0.6 over LAN

### ISSUE THREAD

**Issue by Yugandharjaiswal** [amirsanni/Video-Call-App#1]
well first of all i really appriciate the work. awesome i'm really getting intrest in rachet and webrtc from a while...
so here is my issue the code works fine with chat and all on wamp localhost but i put my wamp online and can access it over my android device over wifi ... using my servers IP 192.168.0.13/video-call-app the page opens and join same room over two phone on same wifi but nothing seems to be happing not even the toast that say connected or not connected to server(As it show on localhost) ... and nothing happens it says offline. 
can you help me run this over LAN(WAMP)

**Comment by amirsanni** [comment]
@Yugandharjaiswal Oh! Sorry for the late response. Do you still have this issue?

**Comment by Yugandharjaiswal** [comment]
Sorry for Late reply
No i had to make changes in My WAMP server
now i'm able to run your Code on My system on WAMP server 
i can run my wamp server on my phones connected on sam network 
and now i can use vedio call on diffrent devices on same network

**Comment by amirsanni** [comment]
Good to hear that.

**Comment by vivekanandpandey** [comment]
HI All 
I have the same Issue,  @Yugandharjaiswal  Please suggest me the changes made by you
