### ISSUE TITLE
Call Recieve Options not visible

### ISSUE THREAD

**Issue by mmg786** [amirsanni/Video-Call-App#10]
Hi,

I have just got your code and tried on my local.The server has been connected .I am testing on my local.One in chrome and other in firefox .Both point to the same room. But the client and remote browser.If i tried to start video call from one browser (client ) and i expected to recieve ring on the other browser (remote). But  the ring starts just on browser and doesn't even rings the other browser and full options (e.g Recieve call,doesntshows the online status etc). All i am getting  "Connected" message in the beginning. The screen is completely dark. and not connecting..

Could you please advise?
See attached screen shot.Thanks

![amirsanni](https://user-images.githubusercontent.com/7581115/35132648-2ca688e0-fcc4-11e7-8d82-e58c25269cd9.png)
@amirsanni

**Comment by amirsanni** [comment]
Is this test on the same device?

**Comment by amirsanni** [comment]
From your screenshot, you're the caller, so you cannot have a **receive call** button. Are you testing on the same device?

**Comment by amirsanni** [comment]
Any update on this issue?
