### ISSUE TITLE
Firefox can’t establish a connection to the server at ws://192.168.1.107:8080/comm.

### ISSUE THREAD

**Issue by anto-christo** [amirsanni/Video-Call-App#12]
Hi,
I followed all the instructions in the README.
The Ratchet server is running properly.
I am using xampp in Windows 10.

After entering the chat room I am getting the following error in console:
`Firefox can’t establish a connection to the server at ws://192.168.1.107:8080/comm.`

![rtc](https://user-images.githubusercontent.com/22641196/37508475-36a356a8-2919-11e8-803b-48e38327b3d0.PNG)

The remote is in offline status. Any help in this regard is appreciated. Thank you.

**Comment by amirsanni** [comment]
Did you start the server?

**Comment by anto-christo** [comment]
Hi, yes, I started the server and it is running properly.
The above error no longer persists. I guess it was due to a wrong IP address.

But now, I am facing a different issue, I am able to only send messages and not receive them. Sometimes I am not able to send or receive as well.

I am trying to understand as to why this is happening. In case you have come across a similar issue, please let me know. Thank you.

**Comment by amirsanni** [comment]
Are you still experiencing this? Ensure both browsers are connected to the chat server and you're accessing the same URL (chat room) in both browsers/devices.

**Comment by anto-christo** [comment]
Hi, sorry for not following up, I got another example project from GitHub that worked for me. Hence, did not try debugging this project. I'm pretty sure there was some mistake from my end. Closing this issue, thank you.
