### ISSUE TITLE
Uncaught DOMException: Failed to execute 'send' on 'WebSocket': Still in CONNECTING state

### ISSUE THREAD

**Issue by sohail0992** [amirsanni/Video-Call-App#13]
I access the cpanel of godaddy through ssh and run the server.php and even tried a cron job but not connecting to web socket .

**Comment by amirsanni** [comment]
Is this issue still pending?

**Comment by tobujin** [comment]
hello, @amirsanni , I have same problem now.
I followed your instruction for online server , but i can't get the websocket.
Then i tried with cron job , but still same issue.
Thanks.

**Comment by amirsanni** [comment]
1. Were you able to successfully start Ratchet server?

2. Are you sure the port you are trying to use is open and not used by another service?

3. Once you're able to start the server, you can then create ratchet as a service on your server. I added another file on how to create a service using start-stop-daemon. You can use that as well.

**Comment by tobujin** [comment]
No, I didn't.
that is my difficulty.

**Comment by amirsanni** [comment]
Welcome.
A cron job is different from a linux service.

It's either you use the instruction in **_ratchet_as_a_service.txt_** or you install start-stop-daemon by using the info in _**install-start-stop-daemon.txt**_ and then create Ratchet as a service following the info in **_create-ratchet-as-a-service-with-daemon.txt_**.

Hope you understand?

**Comment by tobujin** [comment]
thanks for ur help. i will try and let you know.
I hope ur help until success
