### ISSUE TITLE
Chat is offline, even in localhost tabs

### ISSUE THREAD

**Issue by shamidrasool** [amirsanni/Video-Call-App#15]
I tried the app to use its chat feature. When I enter localhost/video-chat-app and press 'Create Room' and 'Enter Room', and I am redirected to a new tab. The problem is that the chat is offline and the following message is displayed "Unable to connect to the chat server! Kindly refresh". When I copy and paste the URL in another tab or even check it on a different computer (e.g http://172.30.2.33/video-call-app/comm.html?room=s79md5385ef) I do not see messages in other window as the status is offline.
I have also made the IP address adjustments as per the Wiki but still I am unable to get it working either in localhost or on LAN. 

Here is the error shown in the console:
`WebSocket connection to 'ws://172.30.2.33:8080/comm' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED
WrappedWebSocket @ blob:http://172.30.2.33/de2a32bd-f36d-49df-a4bf-b0b87fe8fa30:164`

Thanks.

**Comment by amirsanni** [comment]
The chat is offline because the web socket connection failed. Either another program is using the port or you didn't start the Ratchet server. Ensure you start the server and it's running before trying to use the chat feature.
