### ISSUE TITLE
i tried to run it on my local server

### ISSUE THREAD

**Issue by Yugandharjaiswal** [amirsanni/Video-Call-App#16]
i have done all the things correctly
the chat works fine
but when i do vedio or audio call
it shows incoming call but when i answer the call nothing happens
no error in console

**Comment by amirsanni** [comment]
I have updated the scripts to fix this bug. Please try again.

**Comment by Yugandharjaiswal** [comment]
Ok , thanks i will check and let you know

**Comment by alexandrucati** [comment]
i have the same problem ,and its not working with the last update ,i check it today 11/04/20018 i hope you wil find the problem  thx , nice work ;)

**Comment by alexandrucati** [comment]
THIS IS THE ERROR 
Error while calling actor 'domwalker's method 'children' Argument 1 of Window.getComputedStyle is not an object. protocol.js:1041:5
CssLogic.getComputedStyle@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/inspector/css-logic.js:680:10
get computedStyle@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/inspector/node.js:215:29
get displayType@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/inspector/node.js:230:11
initialize@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/inspector/node.js:53:5
cls@resource://devtools/shared/base-loader.js -> resource://devtools/shared/protocol.js:1263:5
_ref@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/inspector/walker.js:331:13
children/<.nodes<@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/inspector/walker.js:673:29
children@resource://devtools/shared/base-loader.js -> resource://devtools/server/actors/inspector/walker.js:673:14
handler@resource://devtools/shared/base-loader.js -> resource://devtools/shared/protocol.js:1198:21
onPacket@resource://devtools/shared/base-loader.js -> resource://devtools/server/main.js:1313:15
receiveMessage@resource://devtools/shared/base-loader.js -> resource://devtools/shared/transport/child-transport.js:66:5
protocol.js:1044:7
Protocol error (unknownError): Argument 1 of Window.getComputedStyle is not an object.

**Comment by alexandrucati** [comment]
InvalidStateError: setRemoteDescription needs to called before addIceCandidate
