### ISSUE TITLE
Connection problem on production and localhost

### ISSUE THREAD

**Issue by karolkarp** [amirsanni/Video-Call-App#18]
When i get version from 04.04.2018 on master it doesnt work properly. When i call video or audio second user can't answer the call and ringtone is still ringing, something is wrong here. Some bug or something, I tried everything.... Then i pull commit "Bug Fixes" from 20.01.2017 and it works good. Uff... So, version from 04.04.2018 doesn't work properly on localhost and prod too. This is important information, because I lost 4 days on it.

**Comment by amirsanni** [comment]
I have updated the scripts to fix this bug. Thank you.
