### ISSUE TITLE
Not working on Firefox

### ISSUE THREAD

**Issue by nauman555** [amirsanni/Video-Call-App#22]
Hi Amir,
Thankyou for the code, i am working on your code, everything is working on Google Chrome but when I am trying on Firebox it's not working.
Its showing remote is offline status.

And when i am calling from Google Chrome to Mozilla  Firefox , everything is Okay with Google Chrome side but on Firefox it showing the error "Unable to use your media sources"
i am running on localhost

**Comment by gildonei** [comment]
With me sometimes it can't connect, so I reload the page until it connect.

To me it only shows online when I have 2 users connected at same room.

**Comment by amirsanni** [comment]
@nauman555 not sure if this is still relevant but that error is as a result of the fact that Chrome is already using your media devices. Try it on two different devices instead.

**Comment by amirsanni** [comment]
> With me sometimes it can't connect, so I reload the page until it connect.
> 
> To me it only shows online when I have 2 users connected at same room.

Online will only show when the other user is connected because the online status is for the remote user, not you.
