### ISSUE TITLE
Error on first time call

### ISSUE THREAD

**Issue by anayinfowind** [amirsanni/Video-Call-App#24]
Hello, 

First of all thanks for this amazing code, i really loved it.

I am having an issue, when a user calls other user for the first time after page refresh, then the call is not connected and it gives error in console "Uncaught (in promise) DOMException: Failed to execute 'createAnswer' on 'RTCPeerConnection': PeerConnection cannot create an answer in a state other than have-remote-offer or have-local-pranswer."  Now when it again calls the call works perfectly fine.

Then is the reciver refresh the page, and caller calls again then again have the same issue for the first time, and on second call it again works fine.

Please help me.

Its something with this code in comm.js

`myPC.createAnswer().then(description).catch(function(e){
                console.log("Error creating answer", e);
                
                showSnackBar("Call connection failed", 15000);
            });`

**Comment by amirsanni** [comment]
@anayinfowind sorry for the late response. I experienced this myself recently and will look into it and update as soon as possible.

Thanks.
