### ISSUE TITLE
Its not working show error

### ISSUE THREAD

**Issue by Lablnet** [amirsanni/Video-Call-App#3]
![screenshot 576](https://user-images.githubusercontent.com/27757785/30807770-1864da72-a1b0-11e7-96ec-419ad3676748.png)

**Comment by amirsanni** [comment]
Is the Ratchet server running?

**Comment by Lablnet** [comment]
I use xampp on Windows just clone this and run 
What is ratchet? help me to run this please

**Comment by amirsanni** [comment]
Please go through the **ReadMe** on How to set it up and running.

**Comment by Lablnet** [comment]
I rad It's not clear where I download server and It's PHP lab or server like appache nigax help me please?

**Comment by amirsanni** [comment]
You don't need to download anything. Just open command prompt, navigate to the Ratchet folder as explained and start the server.

Share teamviewer info if you have, so I can put you through.

**Comment by Lablnet** [comment]
Sir I have team viewer sir I am form Pakistan in Pakistan time is 8:54pm and power is off so please tell me 😊 your email and time that I come online and send you id and pass of team viewer so you can help me please?

**Comment by amirsanni** [comment]
Can't you do it now? amirsanni@gmail.com

**Comment by Lablnet** [comment]
Yes sir not right now Sir tomorrow time please

**Comment by amirsanni** [comment]
3pm GMT+1

**Comment by Lablnet** [comment]
Check your mail I send you mail email lablnet01@gmail.com

**Comment by Lablnet** [comment]
Time now in your convert that

**Comment by Lablnet** [comment]
Sorry for wrong typing
Time now in your country so I convert and easily avilable
