### ISSUE TITLE
connection issue

### ISSUE THREAD

**Issue by saamathur** [amirsanni/Video-Call-App#30]
Hi
I have done this
wsChat = new WebSocket("ws:192.168.1.66:443/videocall/comm");

$allowed_origins = ['192.168.1.66', '443', '192.168.1.66', '192.168.1.66'];

// Run the server application through the WebSocket protocol on port 8080
$app = new Ratchet\App('192.168.1.66', 443, '0.0.0.0');//App(hostname, port, 'whoCanConnectIP', '')

still I am getting error message "Unable to connect to the chat server! Kindly refresh"

**Comment by amirsanni** [comment]
Hi @saamathur ensure the ratchet server is running and properly configured.
