### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by Nagraj137** [amirsanni/Video-Call-App#31]
I am unable to run this package, i am getting bellow error..... please guide me 

Error:
WebSocket connection to 'ws://localhost/video/comm' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by amirsanni** [comment]
Super late response. This error could be as a result of wrong configuration of the ratchet server or maybe the ratchet server was not started.

**Comment by seeguns** [comment]
i unable to run this package too , 

error :
failed: Error during WebSocket handshake: Unexpected response code: 404

how to start ratchet server on windows ?

**Comment by PrakashLakhara** [comment]
I started ratchet server via  php -f server.php  but facing the same error still.

**Comment by amirsanni** [comment]
Please go through the readme on the setup process and ensure the connection is properly configured.
