### ISSUE TITLE
iOS Safari Not Connecting to Chat Server 

### ISSUE THREAD

**Issue by VenkatachalamVE** [amirsanni/Video-Call-App#32]
iOS Safari Not Connecting to Chat Server.
All other Browsers in Desktop, (MAC, Windows, Linux) Works Perfect

**Comment by Nagraj137** [comment]
@VenkatachalamVE it's doesn't worked for me. can you please share what are the steps you have followed.  I am getting below error

WebSocket connection to 'ws://localhost/video/comm' failed: Error during WebSocket handshake: Unexpected response code: 404

**Comment by VenkatachalamVE** [comment]
@Nagraj137  Have you configured PHP Ratchet Server?

**Comment by Nagraj137** [comment]
@VenkatachalamVE Thanks for the reply...
i am not configured PHP Ratchet Server.  Now i am try to run **php server.php** on my localhost but getting below error


```
Fatal error: Uncaught UnexpectedValueException: Invalid domain in D:\projects\vi
deo-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Server\FlashPolicy.php:62
Stack trace:
#0 D:\projects\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\App.php(86):
Ratchet\Server\FlashPolicy->addAllowedAccess('172.17.32.90/vi...', 80)
#1 D:\projects\video-call-app\ws\bin\server.php(18): Ratchet\App->__construct('1
72.17.32.90/vi...', 80, '0.0.0.0')
#2 {main}
  thrown in D:\projects\video-call-app\ws\vendor\cboden\ratchet\src\Ratchet\Serv
er\FlashPolicy.php on line 62
```

**Comment by VenkatachalamVE** [comment]
@Nagraj137 Look this for more information.

http://socketo.me/docs/install
