### ISSUE TITLE
Cannot read property 'version' of undefine

### ISSUE THREAD

**Issue by seeguns** [amirsanni/Video-Call-App#34]
when i change host localhost/ to my ip_address(192.168.1.10)/

i got error : 

Uncaught TypeError: Cannot read property 'version' of undefined
    at adapter.js:29
    at Object.1../chrome/chrome_shim (adapter.js:84)
    at s (adapter.js:1)
    at e (adapter.js:1)
    at adapter.js:1
    at adapter.js:1
    at adapter.js:1

**Comment by amirsanni** [comment]
Something must be missing for you to get that. Ensure you have the files properly set up and try again.

**Comment by seeguns** [comment]
I have finished setting all the configurations, but can't receive video calls, can only chat 

check out the link

http://104.248.154.192/video-call-app/

**Comment by amirsanni** [comment]
Like I noted in the readme, Chrome, Firefox and some other browsers won't give access to media devices without SSL except on localhost. You need to set up SSL for it to work.

**Comment by seeguns** [comment]
I have installed SSL, the video call application can run on Mozilla 

but on PC Chrome it can't ...

* Android , Mobile Chrome is no problem

check the link: https://beta.mycoach.id/video-call-app/
