### ISSUE TITLE
WebSocket connection to 'ws://192.168.64.3:8080/ws/comm' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by romitmewada** [amirsanni/Video-Call-App#36]
<img width="1324" alt="Screenshot 2020-03-20 at 5 02 01 PM" src="https://user-images.githubusercontent.com/1246366/77160557-96db0f00-6acd-11ea-9d3f-5196f31e7120.png">

My ratchet server is running and place my IP address properly. still not connected to server.

Can you help to fix these errors.

**Comment by amirsanni** [comment]
Are you trying on a local server? Can you share what your configuration look like (wc/bin/server.php and js/comm.js)?

**Comment by romitmewada** [comment]
solved
