### ISSUE TITLE
White screen, not able to create room

### ISSUE THREAD

**Issue by LFSveteran** [amirsanni/Video-Call-App#37]
As follow up of Issue #33 , I deleted the vendor directory and did composer install.
I run the server: php server.php
In the browser I open 127.0.0.1:8080/ and only a white screen.
As the readme says http://localhost/video-call-app/ doesn't work
There is a index.html with a create room button so I suppose this index.html is supposed to be called

**Comment by amirsanni** [comment]
Please check your browser console for any error. That page is just plain HTML, CSS and Javascript. There has to be something else wrong. Better still, pull the latest commit and try again.

**Comment by LFSveteran** [comment]
I already pulled the latest version after you removed the vendor directory from the repository
So http://127.0.0.1:8080 would be correct? I haven't seen errors....

**Comment by amirsanni** [comment]
No. The app will run on port 80 by default and the web socket will run on
8080. So you don't need the 8080 in the browser URL. That's only required
in web socket connection.

Amir Sanni

**Comment by LFSveteran** [comment]
in server.php:
 I corrected the incorrect require path to: require '../../vendor/autoload.php';
adjusted the IP:

//set an array of origins allowed to connect to this server
$allowed_origins = ['localhost', '127.0.0.1', '192.168.2.105'];

// Run the server application through the WebSocket protocol on port 8080
$app = new App('192.168.2.105', 8080, '0.0.0.0');//App(hostname, port, 'whoCanConnectIP', '')

in js/comm.js I adjusted the IP:

if(location.protocol === 'http:'){
    wsChat = new WebSocket("ws://192.168.2.105/ws/comm");
}

else{
    wsChat = new WebSocket("wss://192.168.2.105/wss/comm");
}


Killed the apache server, so no other webserver is running anymore.
ran php server.php

From the browser I can access 192.168.2.105:8080 or 127.0.0.1:8080 (same machine) and this gives me the whitepage
If I do the same without 8080 so the normal port 80 is being used I'll get "Failed to connect  / the connection was refused when attempting to contact 192.168.2.105"

**Comment by amirsanni** [comment]
- Start Apache and let it run on port 80.
- Ensure you're referencing the autoload file properly. `require vendor/autoload.php` should be sufficient and that's what it's in the last commit.
- In the http block in comm.js, include the port Ratchet is running on (8080) in the web socket connection URL i.e. `192.168.2.105:8080/comm`

**Comment by LFSveteran** [comment]
If I use " require vendor/autoload.php " I'll get errors:
PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /sources/Video-Call-App/ws/bin/server.php on line 10

Warning: require(vendor/autoload.php): failed to open stream: No such file or directory in /sources/Video-Call-App/ws/bin/server.php on line 10
PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:') in /sources/Video-Call-App/ws/bin/server.php on line 10

Fatal error: require(): Failed opening required 'vendor/autoload.php' (include_path='.:') in /sources/Video-Call-App/ws/bin/server.php on line 10

**Comment by amirsanni** [comment]
That means you don't have the latest update.

Pull the latest commit, then run `composer install` from the root
directory. It will create the vendor directory for you with the
dependencies.

Amir Sanni

**Comment by LFSveteran** [comment]
A fresh pull, "composer install" and the same result....

ls vendor/
autoload.php  cboden  composer  evenement  guzzlehttp  paragonie  psr  ralouphie  ratchet  react  symfony

git diff:

diff --git a/js/comm.js b/js/comm.js
index ab62a71..f81accf 100644
--- a/js/comm.js
+++ b/js/comm.js
@@ -21,11 +21,11 @@ let wsChat;
 const room = getRoom();
 
 if(location.protocol === 'http:'){
-    wsChat = new WebSocket("ws://1410inc.xyz/ws/comm");
+    wsChat = new WebSocket("ws://192.168.2.105:8080/ws/comm");
 }
 
 else{
-    wsChat = new WebSocket("wss://1410inc.xyz/wss/comm");
+    wsChat = new WebSocket("wss://192.168.2.105:8080/wss/comm");
 }
 
 window.addEventListener('load', function(){
diff --git a/ws/bin/server.php b/ws/bin/server.php
index 840bb66..f8b0b2f 100644
--- a/ws/bin/server.php
+++ b/ws/bin/server.php
@@ -13,10 +13,10 @@ use Amir\Comm;
 use Ratchet\App;
 
 //set an array of origins allowed to connect to this server
-$allowed_origins = ['localhost', '127.0.0.1', '1410inc.xyz', 'www.1410inc.xyz'];
+$allowed_origins = ['localhost', '127.0.0.1', '192.168.2.105', 'www.1410inc.xyz'];
 
 // Run the server application through the WebSocket protocol on port 8080
-$app = new App('1410inc.xyz', 8080, '0.0.0.0');//App(hostname, port, 'whoCanConnectIP', '')
+$app = new App('192.168.2.105', 8080, '0.0.0.0');//App(hostname, port, 'whoCanConnectIP', '')
 
 //create socket routes
 //route(uri, classInstance, arrOfAllowedOrigins)

**Comment by amirsanni** [comment]
Do you have TeamViewer? Share if you do.

Amir Sanni
