### ISSUE TITLE
I don't get it running

### ISSUE THREAD

**Issue by webfischi** [amirsanni/Video-Call-App#4]
i tried it with Windows and Kubuntu, with both I am having the same problems. I followed the instructions, but somehow I seem to have missed something important. I've installed Apache 2.4 and PHP7 on my Kubuntu system. The PHP testfile which displays the PHP version is working fine, but when I do "php server.php" the cli does nothing, until I trigger an error by typing "localhost:8080/comm" in the browser. If I type in the recommended test-url from the instruction, the browser can't open the page. When starting the ratchet server, the terminal should display "server startet" I waited 5 minutes for the terminal to do anything on first start. And there should be a possibility to shut down the server, atm I use Ctrl + C to quit, not the ideal solution.

**Comment by amirsanni** [comment]
1. What is this **recommended test-url**?
2. The terminal will only display something if you echo something from the PHP file (comm.php in this case)
3. If you create the Ratchet server as a service on your server, then you'll be able to **start**, **stop** and **restart** it.

**Comment by webfischi** [comment]
I meant http://localhost/video-call-app/ 

I get this error: 
![virtualbox_kubuntu 16 04 lts_31_10_2017_15_49_37](https://user-images.githubusercontent.com/22318963/32230338-35f0127c-be53-11e7-8c5d-75bcf7b8a0fa.png)

**Comment by amirsanni** [comment]
Did you set it up with that name on your server?

**Comment by webfischi** [comment]
How do I do that? According to the instruction I start the ratchet server with `php server.php` and have to enter the url from the second point to test it. There is nothing written that I have to set it up with that name.
An instruction for an easy quick set up with XAMPP would be great.

**Comment by amirsanni** [comment]
Can you share more info on your server set-up?

**Comment by webfischi** [comment]
I'm using the standard installation set-up

**Comment by amirsanni** [comment]
What's the standard setup? For you to be getting that error, it's either the app is saved with another name (mind you, github will append **master** to the name) OR the app is not even in the right directory OR your server is not properly setup.

There is very little I can do if your server is not properly set up.
