### ISSUE TITLE
Steps not properly mentioned. What to do with Server.php file 

### ISSUE THREAD

**Issue by Muddassir1** [amirsanni/Video-Call-App#42]
I'm getting an empty response in the server.php file present in root directory of the app.
Nowhere is it mentioned that what we should do with that file. The line 30 just says:

CURLOPT_URL => "https://global.xirsys.net/_turn/YOUR-CHANNEL-NAME",//Replace 'YOUR-CHANNEL-NAME' with the name of your xirsys channel

Where do I get this channel name? And why isn't this important step mentioned explicitly in the Readme?

**Comment by amirsanni** [comment]
Thanks for the observation. I'll update the readme to include that.

The file is used for getting turn/stun provided by xirsys. You can open a free account there to get the necessary credentials or ditch the file entirely by implementing your own stun/turn.

**Comment by amirsanni** [comment]
ReadMe updated.
