### ISSUE TITLE
everyone can use the chat rooms without any authentication

### ISSUE THREAD

**Issue by xuzhousoft09** [amirsanni/Video-Call-App#46]
Hello amir

I found a problem about video-call-app.
If I put it online, everyone can use the chat rooms.

For example, an anonym can make an url such as 'https://domain-name/video-call-app/comm.php?room=100' to enter a new chat room. Not only that, if he told above url to his friend, they can chat forever.

How to restrict the anonyms? or prevent them from using their selfmade urls to chat with others?

**Comment by amirsanni** [comment]
You'll need to implement authentication based on your need. The repo is
focused on implementing video call with webrtc, nothing more. You can
integrate it into your existing application and put some authentication
around it.

Amir Sanni

**Comment by xuzhousoft09** [comment]
OK, I am implementing.
Thanks!
