### ISSUE TITLE
Could not bind to tcp://0.0.0.0:8080: Address already in use

### ISSUE THREAD

**Issue by oneapple300690** [amirsanni/Video-Call-App#5]
Could you please help me? I try to change my IP address in server.php file but I still could not run php server.php from my cli. Thanks in advance.
P/s: I am using XAMPP to run this.

**Comment by amirsanni** [comment]
I need to know where you made the change AND note that you'll also need to update the IP on the client side.

**Comment by oneapple300690** [comment]
Hi Amir, I just want to try running on my laptop first with different browsers. I tried to change IP address in server.php file to get in run on another device but I could not make it run as well, then I restore it to the original one. Could you please do teamviewer to have a look for me please?

**Comment by oneapple300690** [comment]
I found the issue that when I start Apache server, error "Could not bind to tcp://0.0.0.0:8080: Address already in use" happens. However, if I stop Apache server, I run php server.php without errors but it displays nothing like notifications or something to confirm.

**Comment by amirsanni** [comment]
Are you trying to run it on **0.0.0.0:8080**? Share your teamviewer details

**Comment by oneapple300690** [comment]
I am trying to run it on localhost with different browsers

**Comment by oneapple300690** [comment]
When will you be free for teamviewer?

**Comment by amirsanni** [comment]
Not sure I'll be free today. Perhaps sometime tomorrow. Timezone here is GMT+1

**Comment by oneapple300690** [comment]
Hi there, my timezone here is GMT +12. Now it is 10:47pm. Are you free now?

**Comment by oneapple300690** [comment]
I changed port 8080 to 3030 and could run php server.php without any errors. However, I don't see my camera and chat between two browsers.

**Comment by amirsanni** [comment]
Ensure your client script is trying to connect on that port as well.

**Comment by oneapple300690** [comment]
I am using only my computer to test on different browsers but it could not work properly. Both browsers display "offline" status and could not communicate together. It does not show any errors anymore but it does not work properly.

**Comment by amirsanni** [comment]
Hi @oneapple300690 any success yet? Totally switched off and forgot about this.

**Comment by oneapple300690** [comment]
Hi Amir,
I tried to use for local machine in different browsers but I could not.
Best regards,
Anh

**Comment by amirsanni** [comment]
Any error message in any of the browsers? Which browsers? Which browser are you using on the remote device?

**Comment by oneapple300690** [comment]
I am using macbook pro, firefox browser and google chrome browser. I did
something and it did not show errors any more but I could not see messages
and videos from other browsers.

**Comment by amirsanni** [comment]
@oneapple300690 Is this working now?

**Comment by oneapple300690** [comment]
no, Amir. It is still having same issue and I gave up for a long time ago.

**Comment by amirsanni** [comment]
Unfortunately, I cannot help further. I cannot tell if it has anything to do with your device OR not. No idea. Sorry about that.
