### ISSUE TITLE
Not able to connect to server with IP address even on same same system

### ISSUE THREAD

**Issue by vivekanandpandey** [amirsanni/Video-Call-App#6]
Could you please help me?  I try to connect this video app with IP address (localhost IP: 192.168.1.229)  it could not work  even on same system . but it works fine when i am using localhost in place of IP. i follow your README.md file and change all required as you suggested. please find below my changes in code:
1: change in server.php file
//set an array of origins allowed to connect to this server
$allowed_origins = ['localhost', '127.0.0.1','192.168.1.229'];
// Run the server application through the WebSocket protocol on port 8080
$app = new Ratchet\App('192.168.1.229', 9300, '0.0.0.0');//App(hostname, port, 'whoCanConnectIP', '')

2: Change in comm.js file 
const wsChat = new WebSocket("ws://192.1.168.229:9300/comm");

Even i change IP with 127.0.0.1 it not works. Please suggest how it works

**Comment by amirsanni** [comment]
Unless what you typed here is a typo, the IP in c`onst wsChat = new WebSocket("ws://**192.1.168.229:9300**/comm");` is different from the one in `$app = new Ratchet\App('**192.168.1.229**', 9300, '0.0.0.0');`

**Comment by amirsanni** [comment]
From your configuration, it should work with no problem. Are the two devices on the same network?

**Comment by amirsanni** [comment]
@vivekanandpandey Any update?

**Comment by IbtsamAli** [comment]
sir it is not working even  in single chat app from two different browsers,error occur unable to connect and chat is still offline kindly guide

**Comment by amirsanni** [comment]
Sorry for the late response.

Did you start the Ratchet server?

**Comment by saamathur** [comment]
Hi 
I have done this 
wsChat = new WebSocket("ws:192.168.1.66:443/videocall/comm");

$allowed_origins = ['192.168.1.66', '443', '192.168.1.66', '192.168.1.66'];

// Run the server application through the WebSocket protocol on port 8080
$app = new Ratchet\App('192.168.1.66', 443, '0.0.0.0');//App(hostname, port, 'whoCanConnectIP', '')

still I am getting error message "Unable to connect to the chat server! Kindly refresh"

**Comment by amirsanni** [comment]
1. You don't need 443 in the allowed origins array.

2. Include the hostname you're accessing from the browser in the allowed origins array. e.g. localhost, 127.0.0.1 or whatever host you're using.

**Comment by rahul2cool82** [comment]
Can you teach me how ws will work on localhost
