### ISSUE TITLE
Can't make a call between chat rooms that opened in different networks.

### ISSUE THREAD

**Issue by magentinos** [amirsanni/Video-Call-App#7]
Hello Amir,
First of all, I'd like to say thank you for your great work!

There is an issue for me, it consists in:
I've deployed application to the server. I use ssl and I've configured proxy for that reason.
So my app uses that way to run ratchet:
`// Run the server application through the WebSocket protocol on port 8080
$app = new Ratchet\App('localhost', 8080, '0.0.0.0');

//create socket routes
//route(uri, classInstance, arrOfAllowedOrigins)
$app->route('/comm', new Comm, $allowed_origins);

//run websocket
$app->run();`

I've include domain name of my app in $allowed_origins.

and that way to connect to the web socket server side(Ratchet)
`const wsChat = new WebSocket("wss://domain_name/wss2/comm");`

domain_name is subdomain.
part in vhost configuration that related to proxy looks like
`ProxyPass /wss2/ ws://localhost:8080/`

Everything works well when I call from the same network. For example when I connected to the app by mobile and laptop from another side through the same wifi connection.
Problems start when I connected to app from different networks. For example by mobile device that uses mobile network in my country and from another side by laptop that uses another connection.

Connection is established. I can even make a call and accept from another side. But nothing happen, nothing is heard or seen, sometimes even another side doesn't informed that I've accepted a call(call continues). It looks like some messages of socket are blocked or something like that, but I can't figure out in which direction to move on.

Please let me know if you have any ideas.

Many Thanks
Roman

**Comment by amirsanni** [comment]
Hi Roman, 

Is there any error message in the console?

**Comment by magentinos** [comment]
Nope, I've tried to look through messages that go through web socket channel and it looks like that some of them don't come from another side.

Could be that problem related to "amazon instance".

I've found some info about that
http://blog.flux7.com/web-apps-websockets-with-aws-elastic-load-balancing
I'm going to go in that way to try to fix an issue.

Have you heard something about that? Any thoughts?

Thank you for quick response.

**Comment by amirsanni** [comment]
Haven't heard about that. It's not impossible. Please update with your findings when you're done.

Regards and Thanks

**Comment by amirsanni** [comment]
Any update on this?

**Comment by magentinos** [comment]
Hi Amir,

There was an issue that related to 'iceServers' that we use for RTCPeerConnection. It is not enough to use just 'stun' server to exchange by media packages through the NAT, so we need to add 'turn' server for that reason. That helped to solve my problem.

**Comment by amirsanni** [comment]
Oh! Nice to hear that. Thanks for the update.
