### ISSUE TITLE
Chat Room not coming up

### ISSUE THREAD

**Issue by Divyangna-shrma** [amirsanni/Video-Call-App#8]
![error](https://user-images.githubusercontent.com/35469731/34962354-5c327982-fa69-11e7-8d7a-a4164237ac39.JPG)

Hi amirsanni
I downloaded your code and copied it in my htdocs folder made the required changes-
1) In server.php fille
$allowed_origins = ['localhost', '127.0.0.1','192.168.100.5'];
$app = new Ratchet\App('192.168.100.5', 8080, '0.0.0.0'); 
2)In comm.php file
const wsChat = new WebSocket("ws://192.168.100.5:8080/comm");

when trying to run from my localhost the chat room does not open up and it gives an error of object not found, although the comm.html file is there,
but when clicked on Enter Room simply new tab opens up with object not found error.

Please help.

**Comment by amirsanni** [comment]
This has nothing to do with the chat server. That URL does not exist on your local machine. How did you set up your local server? Is the **comm.html** file in the right directory?

**Comment by Divyangna-shrma** [comment]
![err](https://user-images.githubusercontent.com/35469731/34976969-d7d20274-fabe-11e7-82fd-c9b4716ead6f.JPG)
I installed xampp in C:\ drive on my machine and copied your folder of chat app in htdocs folder of xampp (see the highlighted part) )and the comm.html file exists there.
Also when I run the comm.html directly i.e. not via the index file then the chat room page comes up but nothing gets connected.

**Comment by amirsanni** [comment]
From your URL, you're accessing **video-call-app** while the app directory is named **video-call-app-master**. Remove **-master** from the app folder name and try again.

**Comment by Divyangna-shrma** [comment]
Thanks it was such a silly mistake from my side.
I am now able to enter the chat room but first of all I ran the server.php file from my cli, nothing comes up there but when I opened the chatroom a Message popped up as "Connected to the Server" but still it shows the Remote as offline in the message box and also no messages are being exchanged when I tried to do so. (I have opened two browser windows by following the same chat room entering process via localhost/Video-Chat-App on both the windows)

Where am I going wrong?

**Comment by amirsanni** [comment]
Use two different browsers, preferably Chrome/Firefox/Opera OR run one window in incognito mode.

**Comment by Divyangna-shrma** [comment]
I have only chrome installed so I tried using another window in incognito mode but still nothing happens,
the pop up also doesn't shows up as"connected to the server" although i am running server.php file.

**Comment by amirsanni** [comment]
Install another browser OR use two different devices.
